version: '3.8'

services:

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"

  app:
    container_name: backend
    image: "backend:1.0.0"
    ports:
      - "8080:8080"
    environment:
      - "POSTGRES_DB_SERVER_ADDRESS=db"
      - "POSTGRES_DB_SERVER_PORT=5432"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=example"
    depends_on:
      - db

  frontEnd:
    image: "frontend:latest"
    container_name: "frontend"
    ports:
      - "3000:3000"
    links:
      - app

